apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-deni
  description: hello-deni
  annotations:
    github.com/project-slug: denizhoxha/documentation
    backstage.io/techdocs-ref: github:https://github.com/denizhoxha/documentation
spec:
  type: documentation
  lifecycle: experimental
  owner: deniz hoxha
